version: "3.7"
services:
  guntz-desafio-order-rabbitmq:
    container_name: guntz-desafio-order-rabbitmq
    image: rabbitmq:3-management
    restart: "no"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
    volumes:
      - guntz-desafio-order-rabbitmq:/var/lib/rabbitmq/
      - ./configs/rabbitmq/enabled_plugins:/etc/rabbitmq/enabled_plugins
volumes:
  guntz-desafio-order-rabbitmq: